### ISSUE TITLE
Possible suggestions for release

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/MiNoPy#34]
- Commit Miami-type Pichincha to minsar/samples
- Instead of the mintpy corrections as part of `minopy_template.cfg`, should we follow the minopy processing with `smallbaselineApp.py templatefile --start correct_LOD` ? (Sara:  I have modified some of the mintpy steps based on minopy outputs)
- For Pichincha example use time period with stronger signal ?
- Shall we consider a `create_minopy_runfiles.py` to keep the HPC stuff completely out of MinoPy? 
- rename `run_04_minopy_un-wrap` to `run_04_minopy_unwrap
- in the *cfg file it should be `auto for sequential` `auto for None` to be consistent with mintpy
- there is no `run_02_minopy_inversion`. Should we have one?
- change minopy step `load_int` to `load_ifgrams` ?

Hi @mirzaees : here new comments 7/19:

- when running using idev, snaphu is run in a sequential fashion using just 1 core. Should it not run 16 snaphu jobs in parallel for `compute.num_workers=16`
- In the minopy directory `minopyApp.py --start velocity` (without giving minopy_template.cfg) does not work. Can we make this work? For Mintpy you can do `smallbaselineApp.py --start velocity` without any arguments (as long as there is a `smallbaselineApp.cfg`
- rename `minopy_template.cfg` to `minopyApp.cfg` ? I am not sure. Just a suggestion.  Should we use the term template at all in the documentation, or rather use configuration file?
- example should be without tropospheric correction
- the plotting does not seem to work (see error below, it is somewhat confusing that  smallbaselineApp is shown although minopyApp was used). MintPy now uses native Python for plotting. However. instead of `smallbaselineApp.py --dostep plot` it uses `smallbaselineApp.py --plot`. Maybe we should fix this and use `smallbaselineApp.py --dostep plot` ?
I tried this command but got an error
```
minopyApp.py /scratch/05861/tg851601/PichinchaSenAT18/PichinchaSenAT18.template --dir minopy  --start velocity
```
- I saw some errors/messages regarding `authPath`. Lets consider to do it the same way as for mintpy and for Miami users to require  `minopy.load.autoPath               = yes` and/or  `mintpy.load.autoPath               = yes` set in the `*.cfg` file
- if you run in idev the run_files for unwrapping, etc are generated by the step itself (I think). Would it make sense to generate them at the beginning so that users will see what will be running later?
```
###############################################################
Normal end of Non-Linear time series processing workflow!
##############################################################

******************** plot & save to pic ********************
Traceback (most recent call last):
  File "/home1/05861/tg851601/code/rsmas_insar/sources/MiNoPy/minopy/minopyApp.py", line 819, in <module>
    main()
  File "/home1/05861/tg851601/code/rsmas_insar/sources/MiNoPy/minopy/minopyApp.py", line 81, in main
    app.plot_result()
  File "/home1/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1180, in plot_result
    if self.template['mintpy.compute.cluster']:
KeyError: 'mintpy.compute.cluster'
```

**Comment by falkamelung** [comment]
- Shall we rename `minopyApp.py --job` to `minopyApp.py --jobfiles`  to be consistent with `create_runfiles.py --jobfiles`?

**Comment by falkamelung** [comment]
Number 4 in Pichincha*template is weired...
```
MINOPY.inversion.azimuth_window            = 5
MINOPY.inversion.shp_test                  = ks
MINOPY.inversion.plmethod                  = EMI

########## 4. export the single reference interferograms and unwrap
MINOPY.interferograms.type               = sequential
```
##---------subset (optional):

**Comment by mirzaees** [comment]
> * Commit Miami-type Pichincha to minsar/samples
> * minopyApp.py --help talks about `minopy_wrapper.py` ???
> * where does minopyApp writes files?   In `/minopy` or `/mintpy` directory? It currently says `mintpy`
> 
> ```
> optional arguments:
>   -h, --help            show this help message and exit
>   --dir WORKDIR         specify custom working directory. The default is:
>                         a) current directory, OR
>                         b) $SCRATCHDIR/$projectName/mintpy, if:
> ```
> 
> * Instead of the mintpy corrections as part of `minopy_template.cfg`, should we follow the minopy processinig with `smallbaselineApp.py templatefile --start correct_LOD` ?

**Comment by mirzaees** [comment]
> * Commit Miami-type Pichincha to minsar/samples
> * minopyApp.py --help talks about `minopy_wrapper.py` ???
> * where does minopyApp writes files?   In `/minopy` or `/mintpy` directory? It currently says `mintpy`
> 
> ```
> optional arguments:
>   -h, --help            show this help message and exit
>   --dir WORKDIR         specify custom working directory. The default is:
>                         a) current directory, OR
>                         b) $SCRATCHDIR/$projectName/mintpy, if:
> ```
> 
> * Instead of the mintpy corrections as part of `minopy_template.cfg`, should we follow the minopy processinig with `smallbaselineApp.py templatefile --start correct_LOD` ?

Thank you for suggestions @falkamelung. The first 3, I will do. For the last one, I have modified some of the mintpy steps based on minopy outputs. So I think it is better to have it this way.

**Comment by mirzaees** [comment]
> * Shall we rename `minopyApp.py --job` to `minopyApp.py --jobfiles`  to be consistent with `create_runfiles.py --jobfiles`?
> * install gcc with conda and use that for `python setup.py` ( I had a missing library problem on stampede2, `module purge` solved this.
> * For Pichincha example use time period with stronger signal ?

Yes, all is possible, I will do them

**Comment by mirzaees** [comment]
> Number 4 in Pichincha*template is weired...
> 
> ```
> MINOPY.inversion.azimuth_window            = 5
> MINOPY.inversion.shp_test                  = ks
> MINOPY.inversion.plmethod                  = EMI
> 
> ########## 4. export the single reference interferograms and unwrap
> MINOPY.interferograms.type               = sequential
> ```
> 
> ##---------subset (optional):

I should change the explanation for this one, I agree it is confusing

**Comment by falkamelung** [comment]
**Option names:**
Lets make sure that all long opton names are self-explanatory and follow convention

`unwrap_minopy.py`:
-  it has `--defomax`. Should this be `--displacement_maximum` ? 
- should the `--` options be (nearly) full words?  `--ifg` and `--cor` could be longer

**Comment by falkamelung** [comment]
### Other Suggestions:

- add linefeed to end of all run*files. If you display with `cat` it currently looks weired (`more` is fine)

```
//login3/scratch/05861/tg851601/PichinchaSenAT18/minopy/run_files[1048] cat run_01_minopy_crop
crop_images.py --template /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg --project_dir /scratch/05861/tg851601/PichinchaSenAT18//login3/scratch/05861/tg851601/PichinchaSenAT18/minopy/run_files[1049] 

more run_01_minopy_crop
crop_images.py --template /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg --project_dir /scratch/05861/tg851601/PichinchaSenAT18
```

**Comment by falkamelung** [comment]
When I run `minopyApp.py --start  load_int` it produces a weired `Singularity` message. Is this right?
```
minopyApp.py /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --start load_int
connect /private/tmp/com.apple.launchd.4Qokzp6qca/org.macosforge.xquartz:0: Connection refused
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce

_________________________________________________      

   Miami Non-Linear Inversion software in Python  
          MiNoPy V0.1.0-alpha, 2021-07-09
_________________________________________________

--RUN-at-2021-07-11 22:12:12.579914--
Run routine processing with arg_parser.py on steps: ['load_int', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'write_to_timeseries', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
20210711:221212 * minopyApp.py /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --start load_int
Go to work directory: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy
auto-->auto
25.755:25.9,-80.15:-80.115-->25.755:25.9,-80.15:-80.115
auto-->auto
auto-->auto
copy minopy_template.cfg to inputs directory for backup.
read custom template file: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
update default template based on input custom template
No new option value found, skip updating /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
read default template file: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
WARNING: "processor" not defined in template, it is set to "isce" by default
copy /home1/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/sh/plot_smallbaselineApp.sh to work directory: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy


******************** step - load_int ********************
singularity exec /scratch/05861/tg851601/mgeolab.sif load_int.py --template /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --project /scratch/05861/tg851601/MiamiHighResSenAT48 --output /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/inputs/ifgramStack.h5
SAR platform/sensor : Sen
processor: isce
check auto path setting for Univ of Miami users for processor: isce
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m /scratch/05861/tg851601/MiamiHighResSenAT48/reference/IW3.xml -g /scratch/05861/tg851601/MiamiHighResSenAT48/merged/geom_reference -b /scratch/05861/tg851601/MiamiHighResSenAT48/baselines  -d /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/inverted/interferograms_combine -f *fine*.unw 
connect /private/tmp/com.apple.launchd.4Qokzp6qca/org.macosforge.xquartz:0: Connection refused
['/scratch/05861/tg851601/MiamiHighResSenAT48/reference/data.rsc'] exists and is newer than ['/scratch/05861/tg851601/MiamiHighResSenAT48/reference/IW3.xml'] --> skip.
```

**Comment by mirzaees** [comment]
> **Option names:**
> Lets make sure that all long opton names are self-explanatory and follow convention
> 
> `unwrap_minopy.py`:
> 
> * it has `--defomax`. Should this be `--displacement_maximum` ?
> * should the `--` options be (nearly) full words?  `--ifg` and `--cor` could be longer. Lets check with isce, mintpy

Ok I will correct them

**Comment by mirzaees** [comment]
> ### Other Suggestions:
> * add linefeed to end of all run*files. If you display with `cat` it currently looks weired (`more` is fine)
> 
> ```
> //login3/scratch/05861/tg851601/PichinchaSenAT18/minopy/run_files[1048] cat run_01_minopy_crop
> crop_images.py --template /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg --project_dir /scratch/05861/tg851601/PichinchaSenAT18//login3/scratch/05861/tg851601/PichinchaSenAT18/minopy/run_files[1049] 
> 
> more run_01_minopy_crop
> crop_images.py --template /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg --project_dir /scratch/05861/tg851601/PichinchaSenAT18
> ```

Will be done

**Comment by mirzaees** [comment]
> When I run `minopyApp.py --start load_int` it produces a weired `singularity` message for the `load_int` portion. Is this right?
> 
> ```
> minopyApp.py /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --start load_int
> connect /private/tmp/com.apple.launchd.4Qokzp6qca/org.macosforge.xquartz:0: Connection refused
> This is the Open Source version of ISCE.
> ...
> _________________________________________________      
> 
>    Miami Non-Linear Inversion software in Python  
>           MiNoPy V0.1.0-alpha, 2021-07-09
> _________________________________________________
> 
> --RUN-at-2021-07-11 22:12:12.579914--
> Run routine processing with arg_parser.py on steps: ['load_int', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'write_to_timeseries', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
> --------------------------------------------------
> 20210711:221212 * minopyApp.py /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --start load_int
> Go to work directory: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy
> auto-->auto
> 25.755:25.9,-80.15:-80.115-->25.755:25.9,-80.15:-80.115
> auto-->auto
> auto-->auto
> copy minopy_template.cfg to inputs directory for backup.
> read custom template file: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
> update default template based on input custom template
> No new option value found, skip updating /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
> read default template file: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg
> WARNING: "processor" not defined in template, it is set to "isce" by default
> copy /home1/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/sh/plot_smallbaselineApp.sh to work directory: /scratch/05861/tg851601/MiamiHighResSenAT48/minopy
> 
> 
> ******************** step - load_int ********************
> singularity exec /scratch/05861/tg851601/mgeolab.sif load_int.py --template /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/minopy_template.cfg --project /scratch/05861/tg851601/MiamiHighResSenAT48 --output /scratch/05861/tg851601/MiamiHighResSenAT48/minopy/inputs/ifgramStack.h5
> SAR platform/sensor : Sen
> processor: isce
> ```

You are right, it is a messaging bug, I will correct it

**Comment by falkamelung** [comment]
We have
```
MINOPY.parallel.num_workers           = 4            
```
Can/could we use the MintPy option for that?  Not Sure. Might not be a good idea. Should we then use `mintpy.compute` as in MintPy? 
```
mintpy.compute.maxMemory = auto #[float > 0.0], auto for 4, max memory to allocate in GB
mintpy.compute.cluster   = local #[local / slurm / pbs / lsf / none], auto for none, cluster type
mintpy.compute.numWorker = 32 #[int > 1 / all], auto for 4 (local) or 40 (non-local), num of workers
mintpy.compute.config    = auto #[none / slurm / pbs / lsf ], auto for none (same as cluster), config name
```

**Comment by mirzaees** [comment]
> 1. Use MINOPY.compute ?
> 
> We have:
> 
> ```
> MINOPY.parallel.num_workers           = 4            
> ```
> 
> Can/could we use the MintPy option for that? Not Sure. Might not be a good idea. Should we then use `MINOPY.compute` as in MintPy?
> 
> ```
> mintpy.compute.maxMemory = auto #[float > 0.0], auto for 4, max memory to allocate in GB
> mintpy.compute.cluster   = local #[local / slurm / pbs / lsf / none], auto for none, cluster type
> mintpy.compute.numWorker = 32 #[int > 1 / all], auto for 4 (local) or 40 (non-local), num of workers
> mintpy.compute.config    = auto #[none / slurm / pbs / lsf ], auto for none (same as cluster), config name
> ```
> 
> 1. default  to auto conversion
>    There may be a few 'default' left which probably should be changed to 'auto'
>    grep def minopy_template.cfg
> 
> ```
> MINOPY.interferograms.type               = combine         # [single_reference, sequential, combine, list] default: sequential
> MINOPY.interferograms.list               = bestints.txt    # text file containing the list of interferograms to unwrap, default: None
> ```

1. It is different than mintpy, but yes it can be MINOPY.compute
2. There is nothing other than auto in default template!

**Comment by falkamelung** [comment]
**Minor issues:**
- Some run steps have a leading white space that does not belong there, e.g. `load_int.py` 
```
******************** step - load_int ********************
 load_int.py --template /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg /scratch/05861/tg851601/PichinchaSenAT18/minopy/minopy_template.cfg --project /scratch/05861/tg851601/PichinchaSenAT18 --output /scratch/05861/tg851601/PichinchaSenAT18/minopy/inputs/ifgramStack.h5
SAR platform/sensor : Sen
```

- in the *cfg file it should be `auto for sequential` `auto for None` to be consistent with mintpy
 ```
MINOPY.interferograms.type               = combine         # [single_reference, sequential, combine, list] default: sequential
MINOPY.interferograms.list               = bestints.txt    # text file containing the list of interferograms to unwrap, default: None
```
