### ISSUE TITLE
Other suggestions for release

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/MiNoPy#39]
- Example data: for Pichincha, shall we add what is needed so that mintpy also works? 
- Compilation:
1.   Write out the commands (e.g. `python setup.py` instead of a mysterious `bash $MINOPY_HOME/docs/install`
2.  When you get errors it is unclear whether the compilation was successful. Whey I run `python setup.py` I get the cryptic output below. It also should tell me that everything is installed already (if it is)
```
python setup.py
running build_ext
copying build/lib.linux-x86_64-3.8/utils.cpython-38-x86_64-linux-gnu.so -> 
copying build/lib.linux-x86_64-3.8/invert.cpython-38-x86_64-linux-gnu.so -> 
```
3. To ensure that the conda-installed gcc is used we need  something like
```
make CC=$PYTHON3DIR/bin/x86_64-conda_cos6-linux-gnu-gcc
alias gcc=$PYTHON3DIR/bin/x86_64-conda_cos6-linux-gnu-gcc
```

**Comment by mirzaees** [comment]
Yes we could do that, I will include it in my commits

**Comment by yunjunz** [comment]
You may also want to remove the `__pycache__` directory in the repo.

**Comment by mirzaees** [comment]
@yunjunz Sure, thank you!

**Comment by falkamelung** [comment]
rename `phase_to_range.py` to `invert_network.py`?   
(also say  on "Brief description of steps" that it uses MintPy)

**Comment by yunjunz** [comment]
I would recommend separating jupyter notebooks from the code repo, as the former can be large in size, and not very track-change friendly. 

It would be even better if you could use `git rebase` to remove the jupyter notebook from the minopy repo commit history, before more people are using it. ISCE-2 had this issue before.

**Comment by mirzaees** [comment]
Hi @yunjunz, you are right, we need to move minopy to another repo other than geodesymiami and I wanted to separate notebooks there

**Comment by falkamelung** [comment]
Suggestions to improve "Brief description of processing steps and/or Jupyter Notebook: 
- explain files produced by each step. What is in the "inverted/PATCHES' directory, e.g. what is in the files
`flag.npy  mask_ps.npy  phase_ref.npy  quality.npy  shp.npy` and what does the extension `npy` stands for? Can they be examined to understand details of the processing? How are the PATCHES created? How would locate the patch covering your particular area of interest?
- also explain how u have implemented the writing of results and why you can restart the program at any time
- Explain briefly the files that  are produced:  `phase_series.h5`.  Should/can the quality files get a more meaningful name, such as pta_tempCoherence? They are produced at the end. Briefly explain why
MORE LATER

OTHERS:
- `In phase_inversion.py` don't show so many decimals for the time for completion. One decimal is enough. Currently it says: `Phase inversion of PATCH_7 is Completed in 222.08839631080627 s`

**Comment by falkamelung** [comment]
And I wonder whether we should change the directory structure to facilitate the testing of different networks. One option (there are many) is:
```
minopy_inverted/inputs/slcStack.h5
minopy_sequential/inputs/ifgramStack.h5
minopy_delaunay/inputs/ifgramStack.h5
```

**Comment by falkamelung** [comment]
Thank you for implementing most (or all?) suggestions
