### ISSUE TITLE
Run phase_inversion in parallel

### ISSUE THREAD

**Issue by stoormgeo** [geodesymiami/MiNoPy#49]
Hi, 
Im looking for solution to speedup inversion. Is it suitable if i run commands from phase_inversion runfile in parallel on several compute nodes?
Thx

**Comment by mirzaees** [comment]
Hi @stoormgeo 
Yes, that is exactly what you can do
I myself use minsar to create jobs for each command automatically 
each command runs n patches simultaneously where n is the number of workers you define in template
workers are cores for each node.
so you can run all patches in parallel if you submit each command to a separate node
