### ISSUE TITLE
Unwrapping issue

### ISSUE THREAD

**Issue by stoormgeo** [geodesymiami/MiNoPy#50]
Hi,
If there a way to set the unwrapping parameters manually? 
I played with different parameters in conf.full (NTILEROW and NTILECOL) and run_04_minopy_unwrap_ifgram, but this does not help to solve issue.
Thx

`20211127:010933 * unwrap_ifgram.py --ifg /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/interferograms_single_reference/20190814_20170630/filt_fine.int --coherence /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/quality_average --unwrapped_ifg /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/interferograms_single_reference/20190814_20170630/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 19526 --width 19940 --height 633730.1420114406 --num_tiles 97 --earth_radius 6393121.60859229 --wavelength 0.031228381041666666 -m /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/mask_unwrap

snaphu -f /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/interferograms_single_reference/20190814_20170630/config_all -d /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/interferograms_single_reference/20190814_20170630/filt_fine.int 19940 -o /home/insar/1/Fast/YLP/proc/merged/minopy/inverted/interferograms_single_reference/20190814_20170630/filt_fine.unw --tile 9 10 500 500 --nproc 97

b'number of processors exceeds precomplied limit of 64\n'

Time spent: 0.00015874306360880535 m`

**Comment by mirzaees** [comment]
Hi @stoormgeo 

Unwrapping is a big problem when working in full resolution 
I see your subset is very large and that is going to take hours to unwrap each interferogram, unless the interferograms are coherent
So first, I suggest to use a smaller subset
If you insist on unwrapping the big subset, you need to use the sed command and change number of tiles. run the following in run_files folder:

sed -i 's/--num_tiles 97/--num_tiles 25/g' run_04*

This will change the number of tiles from a total of 97 to 25 if you have at least 25 cores for each node
Then you run the unwrapping run_04. (do not use minopyAppy --step after this)

the other way is to modify the code for number of tiles:

https://github.com/geodesymiami/MiNoPy/blob/56d89aa08eaf4c4dce8f1bc370fa79be9dfc6f91/minopy/minopyApp.py#L461

you need to change 4000000 with a larger number to decrease number of tiles.

If you have a noisy interferogram, then filtering with a larger threshold in step 3 might help
https://github.com/geodesymiami/MiNoPy/blob/56d89aa08eaf4c4dce8f1bc370fa79be9dfc6f91/minopy/defaults/minopyApp.cfg#L70

**Comment by stoormgeo** [comment]
Hi, @mirzaees 
Using sed work well. Thanks!
Will there be any artifacts on edges if process a large image in small chunks?  Or is it better to process the whole image, but using paralleling where possible like in inversion and unwrapping?

> Hi @stoormgeo
> 
> Unwrapping is a big problem when working in full resolution I see your subset is very large and that is going to take hours to unwrap each interferogram, unless the interferograms are coherent So first, I suggest to use a smaller subset If you insist on unwrapping the big subset, you need to use the sed command and change number of tiles. run the following in run_files folder:
> 
> sed -i 's/--num_tiles 97/--num_tiles 25/g' run_04*
> 
> This will change the number of tiles from a total of 97 to 25 if you have at least 25 cores for each node Then you run the unwrapping run_04. (do not use minopyAppy --step after this)
> 
> the other way is to modify the code for number of tiles:
> 
> https://github.com/geodesymiami/MiNoPy/blob/56d89aa08eaf4c4dce8f1bc370fa79be9dfc6f91/minopy/minopyApp.py#L461
> 
> you need to change 4000000 with a larger number to decrease number of tiles.
> 
> If you have a noisy interferogram, then filtering with a larger threshold in step 3 might help
> 
> https://github.com/geodesymiami/MiNoPy/blob/56d89aa08eaf4c4dce8f1bc370fa79be9dfc6f91/minopy/defaults/minopyApp.cfg#L70

**Comment by mirzaees** [comment]
Hi @stoormgeo 
Unwrapping using snaphu in tile mode can be done in two stages. first unwrapping tiles with some overlap (500 pixels by default) then unwrapping the one tile merged result. This is the default process in minopy. I didn't see artifacts from multiple tiles comparing to one tile unwrap but unwrapping errors exist in both cases for sure.

**Comment by stoormgeo** [comment]
Hi @mirzaees 
Is it possible to set tiles size manualy via unwrap_ifgram.py? I can set it directly in snaphu but i am loosing xml/vrt (rmfilter probably) generation in this case.  
Thx

> Hi @stoormgeo Unwrapping using snaphu in tile mode can be done in two stages. first unwrapping tiles with some overlap (500 pixels by default) then unwrapping the one tile merged result. This is the default process in minopy. I didn't see artifacts from multiple tiles comparing to one tile unwrap but unwrapping errors exist in both cases for sure.

**Comment by mirzaees** [comment]
Hi @stoormgeo 
It is possible to edit the code for yourself
You can change the number of tiles in x and y direction:

https://github.com/geodesymiami/MiNoPy/blob/32e9375a493646c7cac5e5e6bfce8b3c7eaeabf4/minopy/unwrap_ifgram.py#L151

x_tile and y_tile can be hard codes in there

**Comment by stoormgeo** [comment]
I am trying to process big and noisy fullframe CSK stripmap data and now can't unwrap any interferogram yet. Playing with snaphu thresholds, defomax, mask and algorithm types with no effects. Fast tiling and out of memory (with no visible memory consuming) before assembling on machine with 96 vCPU and half Tb of memory. 
Does it make sense to try a slight multilooking? But it is not clear how to do it without recalculating the inversion. 
Thx

> Hi @stoormgeo It is possible to edit the code for yourself You can change the number of tiles in x and y direction:
> 
> https://github.com/geodesymiami/MiNoPy/blob/32e9375a493646c7cac5e5e6bfce8b3c7eaeabf4/minopy/unwrap_ifgram.py#L151
> 
> x_tile and y_tile can be hard coded in there

**Comment by mirzaees** [comment]
As I mentioned before the unwrapping of full frame is not suggested, the main problem is as you see, unwrapping. Specially when it is noisy. I do not have a perfect solution for this, but there are a few things you may try.

1. creating a mask to remove areas that are highly decorrelated from unwrapping. it must be in .h5 format and given in template. Once you have it, you need to run step 3 first command (generate_unwrap_mask) before running step 4.

2. The other thing you may try is to use a higher value for filtering in step 3. it is set to 0 by default. After your results are unwrapped using a higher filter value, minopy will remove the filtering effect by adding the integer phase jumps to interferogram before filtering. This is a way to not mess with phase closure. However you can also choose to not remove the filtering effect after unwrapping by setting the following parameter to no. 
https://github.com/geodesymiami/MiNoPy/blob/32e9375a493646c7cac5e5e6bfce8b3c7eaeabf4/minopy/defaults/minopyApp.cfg#L76

**Comment by mirzaees** [comment]
I assume this issue is resolved, I am closing it
