### ISSUE TITLE
incomplete job_submission command written into log file

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/MiNoPy#55]
The `--tmp` is missing in the logged commands. Currently it writes:
```
job_submission.py --template /work2/05861/tg851601/stampede2/insarlab/infiles/famelung/TEMPLATES/HaitiSenDT142.template /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files/run_03_minopy_generate_ifgram --outdir /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files_tmp --numBursts 3 --writeonly
```
If I run with `--tmp` it works fine.  There is also confusion about `minopy/run_files_tmp`.  Sometimes (or always?) it shows up in the log file.  I could not figure out when exactly.

Writing files into `minopy/run_files_tmp` for `minopyApp.py --tmp` (default) (and `minopy/runfiles` for `--no_tmp`) may resolve all confusion.

**Comment by falkamelung** [comment]
Hi @mirzaees 
The above example creates an run_03*.job file but the `copy_data_to_tmp.bash` command  is not right. The last argument containing `phase_series.h5` is missing.

```
copy_data_to_tmp.bash /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files/run_03_minopy_generate_ifgram_3.job /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files/run_03_minopy_generate_ifgram_3 /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files
```


```
copy_data_to_tmp.bash /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files/run_03_minopy_generate_ifgram_3.job /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files/run_03_minopy_generate_ifgram_3 /scratch/05861/tg851601/HaitiSenDT142/minopy/run_files
```

**Comment by mirzaees** [comment]
Hi @falkamelung 

This issue is related to job_submission (minsar) not minopy
please make it in that repo next time. It is fixed now, I am closing the issue
