### ISSUE TITLE
MiNoPy naming suggestions

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/MiNoPy#58]
**- MipliPy - MIami Phase Linking In Python**. (Miami Interferometric Phase LInking)

- MilPy - Miami Insar Linking Phase in pYthon
- MilpPy
- MilipPy = Miami Insar software for Linking of the Interferometric Phase in Python.
- MipalPy Miami Insar PhAse Linking in Python. (MiphalPy)

- MinloPy
- MinliPy
 
- Other terms to add: Full Coherence  (Lets not do Fuc...)
MifucPy, MifucoPy = Miami InSAR Full Coherence software

- Full Resolution ( can we get furious?)
- Minopy = Miami nonlinear phase linking in Python
- MiaplPy= "My Apple Pie" MIAmi Phase Linking"

At a minimum:  MiNoPy --> MinoPy

**Comment by mirzaees** [comment]
MaiplPy decided
